services:
  - type: web
    name: btp-flask-app  # Change to your app name
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app  # Assumes your Flask app is in app.py
    autoDeploy: true